pbiapiapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pbiwebapp.urls') )
]

pbiwebapp/urls.py
from django.urls import path
from . import views


app_name = "pbiwebapp"
urlpatterns = [
    path('', views.IndexView, name="index"),
    path('workpaces/', views.WorkspaceView.as_view(), name="workspaces"),
    path('datasets/', views.DatasetView.as_view(), name="datasets"),
    path('update_capacities/', views.update_capacities, name="update_capacities"),
    path('update_workspaces/', views.update_workspaces, name="update_workspaces"),
    path('update_datasets/', views.update_datasets, name="update_datasets"),
    path('delete_capacity_from_db/<int:v_id>', views.delete_capacity_from_db, name="delete_capacity_from_db"),
    path('delete_workspace_from_db/<int:v_id>', views.delete_workspace_from_db, name="delete_workspace_from_db"),
    path('delete_dataset_from_db/<int:v_id>', views.delete_dataset_from_db, name="delete_dataset_from_db"),
]

pbiwebapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class PowerBI_Setting(models.Model):
    app_id = models.CharField(max_length = 200)
    tenant_id = models.CharField(max_length = 200)
    username = models.CharField(max_length = 200)
    password = models.CharField(max_length = 200)
    insertedDate = models.DateTimeField("Created at:", default = timezone.now())

    def __str__(self):
        return self.username


class Capacity(models.Model):
    powerbi_setting = models.ForeignKey(PowerBI_Setting, on_delete=models.CASCADE)
    capacityId = models.CharField(max_length = 200)
    capacityName = models.CharField(max_length = 200)
    insertedDate = models.DateTimeField("Created at:" , default = timezone.now())

    def __str__(self):
        return self.capacityId


class Workspace(models.Model):
    capacityId = models.ForeignKey(Capacity, on_delete=models.CASCADE)
    workspaceId = models.CharField(max_length = 200)
    workspaceName = models.CharField(max_length = 200)
    insertedDate = models.DateTimeField("Created at:" , default = timezone.now())

    def __str__(self):
        return self.workspaceId


class Dataset(models.Model):
    workspaceId = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    datasetId = models.CharField(max_length = 200)
    datasetName = models.CharField(max_length = 200)
    insertedDate = models.DateTimeField("Created at:" , default = timezone.now())

    def __str__(self):
        return self.datasetId

pbiwebapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import *
from .utils import *
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test
# Create your views here.


def IndexView(request):
    capacities = Capacity.objects.annotate(workspace_count=Count('workspace'))
    # workspaces = Workspace.objects.filter(insertedDate__lte=timezone.now()).order_by("-insertedDate")[:5]
    workspaces = Workspace.objects.annotate(dataset_count=Count('dataset')).order_by('-dataset_count')[:5]
    datasets = Dataset.objects.filter(insertedDate__lte=timezone.now()).order_by("-insertedDate")[:5]
    data = {'capacities': capacities,
            'workspaces': workspaces,
            'datasets': datasets,
            }
    return render(request, 'pbiwebapp/index.html', data)

class WorkspaceView(generic.ListView):
    model = Workspace
    template_name = "pbiwebapp/workspaces.html"
    context_object_name = "workspaces"

    def get_queryset(self):
        queryset = super().get_queryset()
        annotated_queryset = queryset.annotate(dataset_count=Count('dataset')).order_by('-dataset_count')
        return annotated_queryset


class DatasetView(generic.ListView):
    model = Dataset
    template_name = "pbiwebapp/datasets.html"
    context_object_name = "datasets"

    def get_queryset(self):
        queryset = Dataset.objects.filter(insertedDate__lte=timezone.now()).order_by("-insertedDate")
        return queryset



@staff_member_required
def update_capacities(request):
    pbi_settings = PowerBI_Setting.objects.first()
    print(f"1 -- Views -- PBI_SETTINGS ---{pbi_settings}")
    access_token = request_access_token(pbi_settings.app_id,
                                        pbi_settings.tenant_id,
                                        pbi_settings.username,
                                        pbi_settings.password)
    print(f"2 -- Views -- ACCESS TOKEN ---{access_token}")
    func_update_capacities(access_token)
    print(f"3 -- Views -- RUN FUNCTION ---")
    return redirect('pbiwebapp:index')


@staff_member_required
def delete_capacity_from_db(request,v_id):
    c = Capacity.objects.filter(id=v_id)
    c.delete()
    return redirect('pbiwebapp:index')


@staff_member_required
def update_workspaces(request):
    pbi_settings = PowerBI_Setting.objects.first()
    print(f"1 -- Views -- PBI_SETTINGS ---{pbi_settings}")
    access_token = request_access_token(pbi_settings.app_id,
                                        pbi_settings.tenant_id,
                                        pbi_settings.username,
                                        pbi_settings.password)
    print(f"2 -- Views -- ACCESS TOKEN ---{access_token}")
    func_update_workspaces(access_token)
    print(f"3 -- Views -- RUN FUNCTION ---")
    return redirect('pbiwebapp:index')


@staff_member_required
def delete_workspace_from_db(request,v_id):
    c = Workspace.objects.filter(id=v_id)
    c.delete()
    return redirect('pbiwebapp:index')


@staff_member_required
def update_datasets(request):
    pbi_settings = PowerBI_Setting.objects.first()
    print(f"1 -- Views -- PBI_SETTINGS ---{pbi_settings}")
    access_token = request_access_token(pbi_settings.app_id,
                                        pbi_settings.tenant_id,
                                        pbi_settings.username,
                                        pbi_settings.password)
    print(f"2 -- Views -- ACCESS TOKEN ---{access_token}")
    func_update_datasets(access_token)
    print(f"3 -- Views -- RUN FUNCTION ---")
    return redirect('pbiwebapp:index')



@staff_member_required
def delete_dataset_from_db(request,v_id):
    c = Dataset.objects.filter(id=v_id)
    c.delete()
    return redirect('pbiwebapp:index')


@staff_member_required
def workspaces(request):
    return render(request, 'pbiwebapp/workspaces.html')

pbiwebapp/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <title>Application</title>
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap-grid.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap-reboot.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap-utilities.css' %}">
    <link rel="stylesheet" href="{% static 'pbiwebapp/css/bootstrap-utilities.rtl.css' %}">

</head>
<body>

    {% include 'partials/_navbar.html' %}

    <main>
        <div class = "container mt-4">
            {% block content%}
            {% endblock%}
        </div>
    </main>

  {% include 'partials/_footer.html' %}


<script src = "{% static 'pbiwebapp/js/bootstrap.bundle.js'%}" ></script>
<script src = "{% static 'pbiwebapp/js/bootstrap.esm.js'%}" ></script>
<script src = "{% static 'pbiwebapp/js/bootstrap.js'%}" ></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</body>
</html>

pbiwebapp/templates/partials/_footer.html
<footer>
    <div class = "footer py-3 mt-3">
        <div class="container">
            <span class="text-muted">
                iApplication
            </span>
        </div>
    </div>
</footer>

pbiwebapp/templates/partials/_navbar.html
<header>
    <div class="navbar navbar-expand-sm navbar-light bg-light">

        <div class="container">
           <a class="navbar-brand" href="{% url 'pbiwebapp:index' %}">
              <img src="https://static.cdnlogo.com/logos/c/18/ChatGPT_350x350.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
              iApp
           </a>
            <ul class = "navbar-nav ml-auto">
               <li>
                   <a href="{% url 'pbiwebapp:index' %}" class = "nav-link"> Home </a>
               </li>
                <li>
                   <a href="{% url 'pbiwebapp:workspaces' %}" class = "nav-link"> Workspaces </a>
               </li>
               <li>
                  <a href="{% url 'pbiwebapp:datasets' %}" class = "nav-link"> Datasets </a>
              </li>
                <li>
                   <a href="{% url 'admin:index' %}" class = "nav-link"> Admin </a>
               </li>
           </ul>
        </div>
    </div>
</header>

pbiwebapp/templates/pbiwebapp/datasets.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

    <div class="card">
      <h5 class="card-header">Datasets
            <a class="btn btn-success" href="{% url 'pbiwebapp:update_datasets' %}" role="button" style="float: right; font-size: 15px;">Update</a>
      </h5>
        <div class="card-body">
             <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Workspace</th>
                        <th scope="col">Dataset ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% if datasets %}
                        {% for d in datasets %}
                            <tr>
                                <td>{{ d.workspaceId.workspaceName }}</td>
                                <td>{{ d.datasetId }}</td>
                                <td>{{ d.datasetName }}</td>
                                <td>{{ d.insertedDate }}</td>
                                <td>
                                   <a href="{% url 'pbiwebapp:delete_dataset_from_db' v_id=d.id %}">
                                      <button type="button" class="btn btn-outline-danger">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                          </svg>
                                      </button>
                                  </a>
                              </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          <strong>Nothing Here</strong>
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>




<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="display-4">Project</h2>
              <span class="placeholder" style="width: 50%;"></span>
        <span class="placeholder" style="width: 75%;"></span>
        <span class="placeholder" style="width: 25%;"></span>
  </div>
</div>


{% endblock%}

pbiwebapp/templates/pbiwebapp/index.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

<div class="container text-center">

    <div class="card">
      <h5 class="card-header">Capacities
            <a class="btn btn-success" href="{% url 'pbiwebapp:update_capacities' %}" role="button" style="float: right; font-size: 15px;">
                Update
            </a>
      </h5>
        <div class="card-body">
             <table class="table table-hover">
                <thead>
                    <tr>
                      <th scope="col">Capacity ID</th>
                      <th scope="col">Name</th>
                      <th scope="col">Date</th>
                      <th scope="col">Workspace Count</th>
                      <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% if capacities %}
                        {% for c in capacities %}
                            <tr>
                                <td>{{ c.capacityId }}</td>
                                <td>{{ c.capacityName }}</td>
                                <td>{{ c.insertedDate }}</td>
                                <td>{{ c.workspace_count }}</td>
                                <td>
                                   <a href="{% url 'pbiwebapp:delete_capacity_from_db' v_id=c.id %}">
                                      <button type="button" class="btn btn-outline-danger">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                          </svg>
                                      </button>
                                  </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          <strong>Nothing Here</strong>
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <br><hr><br>

    <div class="card">
      <h5 class="card-header">Workspaces (Top 5)
            <a class="btn btn-success" href="{% url 'pbiwebapp:update_workspaces' %}" role="button" style="float: right; font-size: 15px;">Update</a>
      </h5>
        <div class="card-body">
             <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Capacity</th>
                        <th scope="col">Workspace ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Dataset Count</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% if workspaces %}
                        {% for w in workspaces %}
                            <tr>
                                <td>{{ w.capacityId.capacityName }}</td>
                                <td>{{ w.workspaceId }}</td>
                                <td>{{ w.workspaceName }}</td>
                                <td>{{ w.insertedDate }}</td>
                                <td>{{ w.dataset_count }}</td>
                                <td>
                                   <a href="{% url 'pbiwebapp:delete_workspace_from_db' v_id=w.id %}">
                                      <button type="button" class="btn btn-outline-danger">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                          </svg>
                                      </button>
                                  </a>
                              </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          <strong>Nothing Here</strong>
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <br><hr><br>

    <div class="card">
      <h5 class="card-header">Datasets (Top 5)
              <a class="btn btn-success" href="{% url 'pbiwebapp:update_datasets' %}" role="button" style="float: right; font-size: 15px;">Update</a>
      </h5>
        <div class="card-body">
             <table class="table table-hover">
                <thead>
                    <tr>
                      <th scope="col">Workspace</th>
                      <th scope="col">Dataset ID</th>
                      <th scope="col">Name</th>
                      <th scope="col">Date</th>
                      <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% if datasets %}
                        {% for d in datasets %}
                            <tr>
                              <td>{{ d.workspaceId.workspaceName }}</td>
                              <td>{{ d.datasetId }}</td>
                              <td>{{ d.datasetName }}</td>
                              <td>{{ d.insertedDate }}</td>
                              <td>
                                   <a href="{% url 'pbiwebapp:delete_dataset_from_db' v_id=d.id %}">
                                      <button type="button" class="btn btn-outline-danger">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                          </svg>
                                      </button>
                                  </a>
                              </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          <strong>Nothing Here</strong>
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock%}

pbiwebapp/templates/pbiwebapp/workspaces.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

    <div class="card">
      <h5 class="card-header">Workspaces
            <a class="btn btn-success" href="{% url 'pbiwebapp:update_workspaces' %}" role="button" style="float: right; font-size: 15px;">Update</a>
      </h5>
        <div class="card-body">
             <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Capacity</th>
                        <th scope="col">Workspace ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Dataset Count</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% if workspaces %}
                        {% for w in workspaces %}
                            <tr>
                                <td>{{ w.capacityId.capacityName }}</td>
                                <td>{{ w.workspaceId }}</td>
                                <td>{{ w.workspaceName }}</td>
                                <td>{{ w.insertedDate }}</td>
                                <td>{{ w.dataset_count }}</td>
                                <td>
                                   <a href="{% url 'pbiwebapp:delete_workspace_from_db' v_id=w.id %}">
                                      <button type="button" class="btn btn-outline-danger">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                          </svg>
                                      </button>
                                  </a>
                              </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          <strong>Nothing Here</strong>
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>



<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="display-4">Project</h2>
              <span class="placeholder" style="width: 50%;"></span>
        <span class="placeholder" style="width: 75%;"></span>
        <span class="placeholder" style="width: 25%;"></span>
  </div>
</div>


{% endblock%}